version: '2'
services:
  php_dev:
<<<<<<< HEAD
    container_name: php7.3-server
=======
    container_name: php73-server
>>>>>>> 8a1e57dcbc51389cd11b64e1a3d07fb0bf1d002b
    image: gustavoalevato/php7.3-oracle-sqlserver
    ports:
      - "80:80" 
    volumes:
      - ..\application:/var/www/html
      - ..\datasource:/var/www/datasource
      - .\php.ini:/etc/php/7.3/apache2/php.ini
      - .\000-default.conf:/etc/apache2/sites-available/000-default.conf
      - .\xdebug.ini:/etc/php/7.3/mods-available/xdebug.ini
      - ..\srv:/var/www/srv
    restart: always
    entrypoint: bash -c "service apache2 restart && tail -f /dev/null"
    links:
      - mysql_dev
      
  php_54:
    container_name: php5.4
    image: mxmotta/php5.4-apache
    ports:
      - "8080:80" 
    volumes:
      - ..\application:/var/www/html
    restart: always
    entrypoint: bash -c "service apache2 restart && tail -f /dev/null"
    links:
      - mysql_dev

  mysql_dev:
    container_name: mysql_dev
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - D:\mysql\data\:/var/lib/mysql
      - D:\mysql\imports:/opt/imports
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8181:80
    environment:
      - PMA_ARBITRARY=1
    links:
      - mysql_dev