version: '2'
services:
  php_dev:
    container_name: php7.3-oracle-sqlserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:80" 
    volumes:
      - .\html:/var/www/html
      - .\000-default.conf:/etc/apache2/sites-available/000-default.conf
      - .\php.ini:/etc/php/7.3/apache2/php.ini
      - .\apache2.conf:/etc/apache2/apache2.conf
    restart: always
    entrypoint: bash -c "service apache2 restart && tail -f /dev/null"
